# Generated by Django 5.1.6 on 2025-03-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('授課教師', models.CharField(max_length=100)),
                ('課程名稱', models.CharField(max_length=255)),
                ('開課單位', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
