# Generated by Django 5.1.6 on 2025-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_course_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='課程名稱',
            new_name='coursetitle',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='開課單位',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='授課教師',
            new_name='instructor',
        ),
    ]
